#!/usr/bin/env python3
"""
Generate the static, crawlable pages that are derived from js/products.js.

  python3 scripts/build-products.py          # regenerate everything
  python3 scripts/build-products.py --check  # verify everything is current (no writes)

Writes / updates:
  - products/<slug>.html        one page per product (from scripts/product-template.html)
  - <noscript> product lists    between PRODUCT-LINKS markers on shop.html and each shop-*.html
  - sitemap.xml                 via scripts/build-sitemap.py

js/products.js stays the source of truth. This script also validates it
(slugs, SEO fields, images) and cross-checks the checkout-critical fields
against api/catalog.json — it never modifies catalog.json.

Run it after adding or editing a product, then commit the generated files.
"""

import glob
import html
import importlib.util
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import catalog_data as cd  # noqa: E402

ROOT = cd.ROOT
SITE = cd.SITE
TEMPLATE = os.path.join(HERE, "product-template.html")
PRODUCTS_DIR = os.path.join(ROOT, "products")
MARK_START = "<!-- PRODUCT-LINKS:start (generated by scripts/build-products.py) -->"
MARK_END = "<!-- PRODUCT-LINKS:end -->"
RELATED_COUNT = 3


def esc(s):
    return html.escape(s, quote=True)


def money(n):
    return f"${n:.2f}"


def abs_url(path):
    return SITE + path


def cat_href(categories, name):
    return dict(categories)[name]


# ---------------------------------------------------------------- product page

def related_products(p, products):
    by_id = {x["id"]: x for x in products}
    if p.get("related"):
        return [by_id[i] for i in p["related"] if i in by_id and i != p["id"]][:RELATED_COUNT]
    same = [x for x in products if x["category"] == p["category"] and x["id"] != p["id"]]
    idx = products.index(p)
    rotated = products[idx + 1:] + products[:idx]
    others = [x for x in rotated if x["category"] != p["category"]]
    return (same + others)[:RELATED_COUNT]


def image_alt(p, i, total):
    return p["name"] if i == 0 else f"{p['name']} - photo {i + 1} of {total}"


def main_image_html(p):
    src = cd.photos(p)[0]
    return (f'<img src="{esc(src)}" alt="{esc(p["name"])}" fetchpriority="high">')


def thumbs_html(p):
    imgs = p["images"]
    if len(imgs) < 2:
        return ""
    buttons = []
    for i, src in enumerate(imgs):
        vid = cd.is_video(src)
        thumb_src = re.sub(r"\.(mp4|mov|webm|m4v)$", "-poster.jpg", src, flags=re.I) if vid else src
        alt = f"{p['name']} - video" if vid else image_alt(p, i, len(imgs))
        play = '<span class="play">&#9658;</span>' if vid else ""
        buttons.append(
            f'<button type="button" class="{"on" if i == 0 else ""}" data-alt="{esc(alt)}" '
            f'onclick="switchGalleryImage(this,\'{esc(src)}\')" aria-label="Show photo {i + 1} of {len(imgs)}">'
            f'<img src="{esc(thumb_src)}" alt="{esc(alt)}" loading="lazy">{play}</button>'
        )
    return '\n          <div class="ppThumbs" id="galleryThumbs">' + "".join(buttons) + "</div>"


def related_html(p, products, categories):
    rel = related_products(p, products)
    if not rel:
        return ""
    cards = []
    for r in rel:
        prefix = "From " if len(r.get("materials", [])) > 1 else ""
        ph = cd.photos(r)[0]
        cards.append(
            f'        <a class="featuredCard" href="{cd.product_path(r)}">'
            f'<span class="fThumb"><img src="{esc(ph)}" alt="{esc(r["name"])}" loading="lazy"></span>'
            f'<span class="fBody"><span class="fName">{esc(r["name"])}</span>'
            f'<span class="price">{prefix}{money(r["price"])}</span></span></a>'
        )
    return (
        '    <div class="ppRelated">\n'
        '      <h2>Related products</h2>\n'
        '      <div class="ppRelatedRow">\n' + "\n".join(cards) + "\n      </div>\n"
        '      <p class="catLinks"><a href="/shop.html">Browse all products</a></p>\n'
        "    </div>"
    )


def product_jsonld(p, categories):
    data = {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": p["name"],
        "description": p["desc"],
        "image": [abs_url(s) for s in cd.photos(p)],
        "sku": p["id"],
        "brand": {"@type": "Brand", "name": "WeTheCre8ers"},
        "category": p["category"],
        "url": cd.product_url(p),
        "offers": {
            "@type": "Offer",
            "url": cd.product_url(p),
            "price": f"{p['price']:.2f}",
            "priceCurrency": "USD",
        },
    }
    return json.dumps(data, indent=2, ensure_ascii=False).replace("</", "<\\/")


def breadcrumb_jsonld(p, categories):
    data = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE + "/"},
            {"@type": "ListItem", "position": 2, "name": p["category"], "item": SITE + cat_href(categories, p["category"])},
            {"@type": "ListItem", "position": 3, "name": p["name"], "item": cd.product_url(p)},
        ],
    }
    return json.dumps(data, indent=2, ensure_ascii=False).replace("</", "<\\/")


def render_product_page(p, products, categories):
    tpl = open(TEMPLATE, encoding="utf-8").read()
    values = {
        "TITLE": esc(cd.seo_title(p)),
        "META_DESC": esc(cd.seo_desc(p)),
        "URL": cd.product_url(p),
        "OG_IMAGE": abs_url(cd.photos(p)[0]),
        "JSONLD_PRODUCT": product_jsonld(p, categories),
        "JSONLD_BREADCRUMBS": breadcrumb_jsonld(p, categories),
        "CAT_HREF": cat_href(categories, p["category"]),
        "CATEGORY": esc(p["category"]),
        "NAME": esc(p["name"]),
        "PRICE": money(p["price"]),
        "DESC": esc(p["desc"]),
        "ID": esc(p["id"]),
        "MAIN_IMAGE": main_image_html(p),
        "THUMBS": thumbs_html(p),
        "RELATED": related_html(p, products, categories),
    }
    out = tpl
    for k, v in values.items():
        out = out.replace("{{" + k + "}}", v)
    leftover = re.findall(r"\{\{[A-Z_]+\}\}", out)
    if leftover:
        raise SystemExit(f"{p['id']}: unfilled template placeholders {leftover}")
    return out


# ------------------------------------------------------ <noscript> link blocks

def noscript_block(page, products, categories):
    """Generated <noscript> product list for shop.html or a shop-*.html page."""
    def link(p):
        return f'<a href="{cd.product_path(p)}">{esc(p["name"])}</a>'

    if page == "/shop.html":
        rows = []
        for name, href in categories:
            names = "; ".join(link(p) for p in products if p["category"] == name)
            rows.append(f'<a href="{href}">{esc(name)}</a>: {names}')
        body = ('<p class="catLinks">JavaScript is needed to filter products and add items to your cart. '
                "Products by category:<br>\n        " + "<br>\n        ".join(rows) + "\n      </p>")
    else:
        name = next(n for n, h in categories if h == page)
        names = "; ".join(link(p) for p in products if p["category"] == name)
        body = ('<p class="catLinks">JavaScript is needed to add items to your cart. '
                f'Products in this category: {names}. <a href="/shop.html">Browse all products</a>.</p>')
    return f"{MARK_START}\n    <noscript>\n      {body}\n    </noscript>\n    {MARK_END}"


def apply_noscript(text, block):
    if MARK_START in text:
        pat = re.compile(re.escape(MARK_START) + r".*?" + re.escape(MARK_END), re.S)
        return pat.sub(lambda m: block, text, count=1)
    # first run: replace the hand-written <noscript> that follows the product grid
    grid = '<div class="grid" id="productGrid"></div>'
    pat = re.compile(re.escape(grid) + r"\s*<noscript>.*?</noscript>", re.S)
    if not pat.search(text):
        raise SystemExit("could not find the product grid / <noscript> block to replace")
    return pat.sub(lambda m: grid + "\n    " + block, text, count=1)


# ------------------------------------------------------------------------ main

def load_sitemap_module():
    spec = importlib.util.spec_from_file_location("build_sitemap", os.path.join(HERE, "build-sitemap.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def planned_outputs(products, categories):
    """{absolute path: expected text} for every generated file."""
    out = {}
    for p in products:
        out[os.path.join(PRODUCTS_DIR, p["slug"] + ".html")] = render_product_page(p, products, categories)
    pages = ["/shop.html"] + [h for _, h in categories]
    for page in pages:
        path = os.path.join(ROOT, page.lstrip("/"))
        text = open(path, encoding="utf-8").read()
        out[path] = apply_noscript(text, noscript_block(page, products, categories))
    sm = load_sitemap_module()
    out[sm.OUT] = sm.build_xml(products, categories)
    return out


def main():
    check = "--check" in sys.argv
    products = cd.load_products()
    categories = cd.load_categories()

    problems = cd.validate(products, categories) + cd.check_against_catalog(products)
    if problems:
        print("Catalog problems:")
        for pr in problems:
            print("  -", pr)
        sys.exit(1)

    outputs = planned_outputs(products, categories)
    stale = []
    for path, text in outputs.items():
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current != text:
            stale.append(path)
            if not check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(text)

    expected_pages = {p for p in outputs if p.startswith(PRODUCTS_DIR)}
    orphans = [f for f in glob.glob(os.path.join(PRODUCTS_DIR, "*.html")) if f not in expected_pages]
    if orphans and not check:
        for f in orphans:
            os.remove(f)

    rel = lambda p: os.path.relpath(p, ROOT)
    if check:
        bad = [rel(p) for p in stale] + [rel(p) + " (no longer in products.js)" for p in orphans]
        if bad:
            print("STALE generated files — run: python3 scripts/build-products.py")
            for b in bad:
                print("  -", b)
            sys.exit(1)
        print(f"OK: {len(products)} product pages, {len(categories) + 1} noscript lists, sitemap.xml are current;")
        print("    products.js matches api/catalog.json (id, name, price, frameAddon, needsPhoto)")
        return

    print(f"Catalog OK: {len(products)} products; products.js matches api/catalog.json")
    print(f"Wrote/updated {len(stale)} file(s)" + (f", removed {len(orphans)} orphan page(s)" if orphans else ""))
    for p in stale:
        print("  ", rel(p))


if __name__ == "__main__":
    main()
